#!/bin/sh
while read file
do
        case "$1" in
        "d")
                trash "$file" ;;
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "c")
                echo -n "$file" | xsel -selection clipboard ;;
        "w")
                feh --bg-scale "$file" ;;
        esac
done
