# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html


# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Turn on Qt HighDPI scaling.
c.qt.highdpi = True

# Which Chromium process model to use.
c.qt.process_model = "process-per-site"

# Additional arguments to pass to Qt, without leading --.
c.qt.args = ["enable-native-gpu-memory-buffers", "enable-gpu-rasterization", "use-gl=egl", "ignore-gpu-blacklist", "num-raster-threads=4"]

# Default zoom level.
c.zoom.default = "100%"

c.downloads.location.directory = '~/tmp'

# Remove downloads after 5 seconds.
c.downloads.remove_finished = 5

# Where to show the downloaded files.
c.downloads.position = 'bottom'

# Disable history
c.completion.web_history.max_items = 0
# Save 500 last commands
c.completion.cmd_history_max_items = 500

# Use best match while completion
c.completion.use_best_match = True

# Do not close command window when only one item left
c.completion.quick = False

# Require a confirmation before quitting the application.
c.confirm_quit = ['downloads']

# Allow websites to request geolocations.
c.content.geolocation = False

# Enable plugins in Web pages.
c.content.plugins = True

# Proxy to use.
c.content.proxy = 'system'

# c.content.user_stylesheets = [""]

# Disable cache
# c.content.cache.size = 0

c.content.cache.maximum_pages = 20
# Which cookies to accept.
c.content.cookies.accept = 'all'

# Enable pdfjs
c.content.pdfjs = True

# Automatically start playing `<video>` elements.
c.content.autoplay = False

# Default encoding to use for websites.
# The encoding must be a string describing an encoding such as _utf-8_, _iso-8859-1_, etc.
c.content.default_encoding = 'utf-8'

# Save session
c.auto_save.session= False

# Enable spellchecking
c.spellcheck.languages = ['en-US', 'ru-RU']

# Enable JavaScript.
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable smooth scrolling for web pages. Note smooth scrolling does not
# work with the `:scroll-px` command.
c.scrolling.smooth = False

# Show scrolling bar
c.scrolling.bar = "always"

# Padding (in pixels) around text for tabs.
c.tabs.padding = {'bottom': 1, 'left': 1, 'right': 1, 'top': 1}

# Open blank page when close last tab
c.tabs.last_close = 'default-page'

# Open new tabs (middleclick/ctrl+click) in the background.
c.tabs.background = True

# Format to use for the tab title.
c.tabs.title.format = '[{index}] {current_title}'

# Maximum width (in pixels) of tabs (-1 for no maximum).
c.tabs.max_width = 300

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# c.url.default_page = 'https://ddg.gg'
c.url.default_page = 'qute://bookmarks'

# Page(s) to open at the start.
# c.url.start_pages = 'https://start.duckduckgo.com/'
c.url.start_pages = 'qute://bookmarks'

# Hide the window decoration. This setting requires a restart on Wayland.
c.window.hide_decoration = True

# Text color of the completion widget. May be a single color to use for

# all columns or a list of three colors, one for each column.
c.colors.completion.fg = '#D5C4A1'

# Background color of the completion widget for odd rows.
c.colors.completion.odd.bg = '#333333'

# Background color of the completion widget for even rows.
c.colors.completion.even.bg = '#202020'

# Foreground color of the selected completion item.
c.colors.completion.item.selected.fg = '#FFFFFF'

# Background color of the selected completion item.
c.colors.completion.item.selected.bg = '#558598'

# Top border color of the completion widget category headers.
c.colors.completion.item.selected.border.top = '#151515'

# Bottom border color of the selected completion item.
c.colors.completion.item.selected.border.bottom = '#151515'

# Foreground color of the matched text in the completion.
c.colors.completion.match.fg = '#D75F5F'

# Foreground color of the statusbar.
c.colors.statusbar.normal.fg = '#D5C4A1'

# Background color of the statusbar.
c.colors.statusbar.normal.bg = '#202020'

# Foreground color of the statusbar in command mode.
c.colors.statusbar.command.fg = '#D4C5A1'

# Background color of the statusbar in command mode.
c.colors.statusbar.command.bg = '#202020'

# Default foreground color of the URL in the statusbar.
c.colors.statusbar.url.fg = '#D5C4A1'

# Foreground color of the URL in the statusbar on error.
c.colors.statusbar.url.error.fg = '#D75F5F'

# Foreground color of the URL in the statusbar on successful load (http).
c.colors.statusbar.url.success.http.fg = '#84EDB9'

# Foreground color of the URL in the statusbar on successful load
# (https).
c.colors.statusbar.url.success.https.fg = '#8FEE96'

# Foreground color of the URL in the statusbar when there's a warning.
c.colors.statusbar.url.warn.fg = '#CD950C'

# Background color of the tab bar.
c.colors.tabs.bar.bg = '#282828'

# Foreground color of unselected odd tabs.
c.colors.tabs.odd.fg = '#707070'

# Background color of unselected odd tabs.
c.colors.tabs.odd.bg = '#3C3836'

# Foreground color of unselected even tabs.
c.colors.tabs.even.fg = '#707070'

# Background color of unselected even tabs.
c.colors.tabs.even.bg = '#3C3836'

# Foreground color of selected odd tabs.
c.colors.tabs.selected.odd.fg = '#EBDBB2'

# Background color of selected odd tabs.
c.colors.tabs.selected.odd.bg = '#1D2021'

# Foreground color of selected even tabs.
c.colors.tabs.selected.even.fg = '#EBDBB2'

# Background color of selected even tabs.
c.colors.tabs.selected.even.bg = '#1D2021'

# Foreground color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.fg = '#707070'

# Background color of pinned unselected odd tabs.
c.colors.tabs.pinned.odd.bg = '#3C3836'

# Foreground color of pinned unselected even tabs.
c.colors.tabs.pinned.even.fg = '#707070'

# Background color of pinned unselected even tabs.
c.colors.tabs.pinned.even.bg = '#3C3836'

# Foreground color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.fg = '#D5C4A1'

# Background color of pinned selected odd tabs.
c.colors.tabs.pinned.selected.odd.bg = '#1D2021'

# Foreground color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.fg = '#d5c4a1'

# Background color of pinned selected even tabs.
c.colors.tabs.pinned.selected.even.bg = '#1D2021'


# Fonts
# Default monospace fonts.
# Whenever "monospace" is used in a font setting, it's replaced with the fonts listed here.
c.fonts.default_family = ["monospace"]

# Default font families to use.
# Whenever "default_family" is used in a font setting, it's replaced with the fonts listed here.
# If set to an empty value, a system-specific monospace default is used.
c.fonts.default_size = "10pt"

# Font used in the completion categories.
c.fonts.completion.category = 'bold 10pt monospace'

# Font used in the completion widget.
c.fonts.completion.entry = '10pt monospace'

# Font used for the debugging console.
c.fonts.debug_console = '10pt monospace'

# Font used for the downloadbar.
c.fonts.downloads = '10pt monospace'

# Font used for the hints.
c.fonts.hints = 'bold 10pt monospace'

# Font used in the keyhint widget.
c.fonts.keyhint = '10pt monospace'

# Font used for error messages.
c.fonts.messages.error = '10pt monospace'

# Font used for info messages.
c.fonts.messages.info = '10pt monospace'

# Font used for warning messages.
c.fonts.messages.warning = '10pt monospace'

# Font used for prompts.
c.fonts.prompts = '10pt monospace'

# Font used in the statusbar.
c.fonts.statusbar = '10pt monospace'

# Font used in the tab bar.
c.fonts.tabs.selected = '10pt monospace'

# Font used in the tab bar.
c.fonts.tabs.unselected = '10pt monospace'

# Web font
# Font family for standard fonts.
c.fonts.web.family.standard = 'Liberation Sans'

# Font family for fixed fonts.
c.fonts.web.family.fixed = 'Liberation Mono'

# Font family for serif fonts
c.fonts.web.family.serif = 'Liberation Serif'

# Font family for sans-serif fonts.
c.fonts.web.family.sans_serif = 'Liberation Sans'

# Font family for cursive fonts.
c.fonts.web.family.cursive = 'Liberation Sans'

# Default font size (in pixels) for regular text.
c.fonts.web.size.default = 10

# Default font size (in pixels) for fixed-pitch text.
c.fonts.web.size.default_fixed = 10

# Hard minimum font size (in pixels).
c.fonts.web.size.minimum = 10

# Minimum logical font size (in pixels) that is applied when zooming out.
c.fonts.web.size.minimum_logical = 10
