# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Turn on Qt HighDPI scaling.
c.qt.highdpi = True

# Default zoom level.
c.zoom.default = "100%"

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
c.downloads.location.directory = '~/downloads'

# Remove downloads after 5 seconds.
c.downloads.remove_finished = 5

# Where to show the downloaded files.
c.downloads.position = 'bottom'

# Disable history
c.completion.web_history.max_items = 0
# Save 500 last commands
c.completion.cmd_history_max_items = 500

# Use best match while completion
c.completion.use_best_match = True

# Do not close command window when only one item left
c.completion.quick = False

# Require a confirmation before quitting the application.
c.confirm_quit = ['downloads']

# Allow websites to request geolocations.
c.content.geolocation = False

# Enable plugins in Web pages.
c.content.plugins = True

# Proxy to use.
c.content.proxy = 'system'

# Disable cache
# c.content.cache.size = 0

# Which cookies to accept.
c.content.cookies.accept = 'all'

# Enable pdfjs
c.content.pdfjs = True

# Save session
c.auto_save.session= False

# Enable spellchecking
c.spellcheck.languages = ['en-US', 'ru-RU']

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable smooth scrolling for web pages. Note smooth scrolling does not
# work with the `:scroll-px` command.
# Type: Bool
c.scrolling.smooth = False

# Show scrolling bar
c.scrolling.bar = "always"

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = {'bottom': 4, 'left': 4, 'right': 4, 'top': 4}

# Open blank page when close last tab
c.tabs.last_close = 'blank'

# Open new tabs (middleclick/ctrl+click) in the background.
c.tabs.background = True

# Format to use for the tab title.
c.tabs.title.format = '{audio}{index}: {current_title}'

# Maximum width (in pixels) of tabs (-1 for no maximum).
c.tabs.max_width = 300

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
# c.url.default_page = 'https://ddg.gg'
c.url.default_page = 'about:blank'

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
# c.url.start_pages = 'https://start.duckduckgo.com/'
c.url.start_pages = 'about:blank'

# Hide the window decoration.  This setting requires a restart on
# Wayland.
# Type: Bool
c.window.hide_decoration = False

# Text color of the completion widget. May be a single color to use for

# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = '#d5c4a1'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#333333'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#202020'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#8fee96'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#151515'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#151515'

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#d75f5f'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#d5c4a1'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#202020'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#d4c5a1'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#202020'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#d5c4a1'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#d75f5f'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#84edb9'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#8fee96'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#cd950c'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#202020'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#707070'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#202020'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#707070'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#202020'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#d5c4a1'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#202020'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#d5c4a1'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#202020'

# Default monospace fonts.
# Whenever "monospace" is used in a font setting, it's replaced with the fonts listed here.
c.fonts.monospace = '"Source Code Pro"'

# Font used in the completion categories.
# Type: QtFont
c.fonts.completion.category = 'bold 9pt monospace'

# Font used in the completion widget.
# Type: QtFont
c.fonts.completion.entry = '9pt monospace'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '9pt monospace'

# Font used for the downloadbar.
# Type: QtFont
c.fonts.downloads = '9pt monospace'

# Font used for the hints.
# Type: QtFont
c.fonts.hints = 'bold 9pt monospace'

# Font used in the keyhint widget.
# Type: QtFont
c.fonts.keyhint = '9pt monospace'

# Font used for error messages.
# Type: QtFont
c.fonts.messages.error = '9pt monospace'

# Font used for info messages.
# Type: QtFont
c.fonts.messages.info = '9pt monospace'

# Font used for warning messages.
# Type: QtFont
c.fonts.messages.warning = '9pt monospace'

# Font used for prompts.
# Type: QtFont
c.fonts.prompts = '9pt monospace'

# Font used in the statusbar.
c.fonts.statusbar = '9pt monospace'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '9pt monospace'


## Web font

# Font family for standard fonts.
c.fonts.web.family.standard = 'Droid Sans'

# Font family for fixed fonts.
c.fonts.web.family.fixed = 'Droid Sans Mono'

# Font family for serif fonts
c.fonts.web.family.serif = 'Droid Serif'

# Font family for sans-serif fonts.
c. fonts.web.family.sans_serif = 'Droid Sans Serif'

# Font family for cursive fonts.
c.fonts.web.family.cursive = 'Droid Sans'

# Default font size (in pixels) for regular text.
c.fonts.web.size.default = 18

# Default font size (in pixels) for fixed-pitch text.
c.fonts.web.size.default_fixed = 18

# Hard minimum font size (in pixels).
c.fonts.web.size.minimum = 18

# Minimum logical font size (in pixels) that is applied when zooming out.
c.fonts.web.size.minimum_logical = 6

# Bindings for normal mode
config.bind(';M', 'hint --rapid links spawn umpv {hint-url}')
config.bind('M', 'hint links spawn umpv {hint-url}')
config.bind('m', 'spawn umpv {url}')
