[accounts.fastmail]
default = true
folder = "Inbox"

backend.type = "imap"
backend.host = "imap.fastmail.com"
backend.port = 993
backend.encryption = "tls"
backend.login = "ed@gnkv.io"

backend.auth.type = "password"
backend.auth.cmd = "pass show core/imap.fastmail.com"

on-message-added.cmd = "mbsync -Va"
on-message-added.notify.summary = "{recipient}: new message from {sender}"
on-message-added.notify.body = "{subject}"
