display-name = "Ed Ganiukov"
downloads-dir = "/home/ed/tmp"
signature = "BR,\nEd Ganiuikov"

[default]
default = true
email = "ed@gnkv.io"

backend = "imap"
imap-host = "imap.fastmail.com"
imap-port = 993
imap-login = "ed@gnkv.io"
imap-auth = "passwd"
imap-passwd = { cmd = "pass show core/imap.fastmail.com" }
imap-watch-cmds = ["/usr/bin/mbsync -Va"]

sender = "smtp"
smtp-host = "smtp.fastmail.com"
smtp-port = 465
smtp-login = "ed@gnkv.io"
smtp-auth = "passwd"
smtp-passwd = { cmd = "pass show core/smtp.fastmail.com" }
