vim9script

plug#begin('~/.vim/plugged')

# Plugins
# https://github.com/junegunn/vim-plug

# Basic
Plug 'preservim/nerdtree'
Plug 'jlanzarotta/bufexplorer'
Plug 'tpope/vim-commentary'
# Git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
# LSP
Plug 'prabirshrestha/vim-lsp'
Plug 'lifepillar/vim-mucomplete'

plug#end()

set nocompatible
filetype off

filetype plugin indent on
syntax on

set t_Co=256
set t_ut=

colorscheme off

set encoding=utf-8

set wildmenu
set wildoptions-=pum
set wildignore+=.git/,.direnv/
set completeopt=menuone,popup,noselect

set nospell
set hidden
set noerrorbells
set novisualbell
set t_vb=

set modeline
set modelines=1
set mouse=a

set ignorecase
set smartcase

set nobackup
set nowb
set noswapfile

set noshowmode
set showmatch
set matchtime=2
set showcmd
set autoread

set scrolljump=1
set scrolloff=4
set backspace=2

set conceallevel=0
set nofoldenable

set number
set signcolumn=yes
set pumheight=20
set textwidth=120
set linebreak
set colorcolumn=120
set cursorline
set cursorcolumn

set pastetoggle=<F2>
set nopaste
set clipboard=unnamedplus

set listchars=tab:>\ ,nbsp:.,trail:.
set list

set wrap
set formatoptions=qrn1j

set autoread

set autoindent
set smartindent
set noexpandtab
set tabstop=4
set shiftwidth=4
set shiftround

set splitright
set splitbelow

set shortmess+=c
set laststatus=2

def g:StatusLineMode(): string
	var modes = {
		'n': 'NORMAL',
		'i': 'INSERT',
		'R': 'REPLACE',
		'v': 'VISUAL',
		'V': 'V-LINE',
		"\<C-v>": 'V-BLOCK',
		'c': 'COMMAND',
		's': 'SELECT',
		'S': 'S-LINE',
		"\<C-s>": 'S-BLOCK',
		't': 'TERMINAL'
	}
	return get(modes, mode(), '[NONE]')
enddef

def g:GitStatus(): string
  var [a,m,r] = g:GitGutterGetHunkSummary()
  return printf('+%d ~%d -%d', a, m, r)
enddef

set statusline=
set statusline+=%#Comment#[%n]%*
set statusline+=%#PmenuSel#\ %{g:StatusLineMode()}%{&paste?':PASTE':''}\ %*	# mode and paste indicator
set statusline+=\ %.50f\ %m\ %r	# filepath and modified flag
set statusline+=%{g:GitStatus()}

set statusline+=%=
set statusline+=%{&ff}	# file format
set statusline+=\ \|\ %{&fenc!=#""?&fenc:&enc}	# file enconding
set statusline+=\ \|\ %{&ft!=#""?&ft:"[none]"}	# file type
set statusline+=\ \|\ %p%%\ %l:%c\ %* # percentage and lineinfo

# fix cursor in INSERT mode
&t_SI = "\e[5 q"
&t_EI = "\e[2 q"

# yank to the EOL
nnoremap Y y$
# delete without yanking
nnoremap <leader>d "_d
vnoremap <leader>d "_d
# replace selected text without yanking
vnoremap <leader>p "_dP"

noremap j gj
noremap k gk

# indent
nmap < <<
nmap > >>
vnoremap < <gv
vnoremap > >gv

nnoremap <F5> :set list!<CR>
inoremap <F5> <Esc>:set list!<CR>a
nnoremap <leader><space> :nohlsearch<CR>

# quickfix
# close
nnoremap <silent>qc :cclose<CR>
nnoremap <silent>qf :copen<CR>

# switch
nnoremap <Down> :cn!<CR>
nnoremap <Up> :cp!<CR>
nnoremap qn :cn!<CR>
nnoremap qp :cp!<CR>

# buffers switch
nnoremap fn :bn!<CR>
nnoremap fp :bp!<CR>
nnoremap fd :bd<CR>

# disable arrows
# noremap <Up> <NOP>
# noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

# expand opening-brace
inoremap {<CR> {<CR>}<Esc>O

# move lines up and down with <Alt-down> & <Alt-up> keys
nnoremap <A-down> :m+<CR>=gv
nnoremap <A-up> :m-2<CR>=gv
vnoremap <A-down> :m'>+<CR>gv=gv
vnoremap <A-up> :m-2<CR>gv=gv

cnoreabbrev Wq wq
cnoreabbrev Wa wa

# trailing whitespaces
match ErrorMsg '\s\+$'

nnoremap <leader>t  :ter<CR>

# fuzzy finder
#
def g:Fzf(choice_cmd: string, vim_cmd: string)
	var output = ''
	try
		output = system(choice_cmd .. ' | fzf --height=40%')
	catch /Vim:Interrupt/
		# do not fail on errors from ^C, allow redraw! below
	endtry
	redraw!
	if v:shell_error == 0 && !empty(output)
		exec vim_cmd .. ' ' .. output
	endif
enddef

nnoremap <leader>f :call g:Fzf('rg --files', ':e')<CR>

# buffers
#
def g:FzfBuffer()
  var bufnrs: list<number> = filter(range(1, bufnr('$')), 'buflisted(v:val)')
  var buffers = mapnew(bufnrs, 'bufname(v:val)')
  call g:Fzf('echo "' .. join(buffers, "\n") .. '"', ':b')
enddef

nnoremap <leader>bb :call g:FzfBuffer()<CR>

# grep
#
set grepprg=rg\ --vimgrep
set grepformat=%f:%l:%c:%m

command! -nargs=+ G execute 'silent grep!' <q-args>
nnoremap <leader>g :silent grep! <C-R><C-W><CR>

augroup quickfix
	au QuickFixCmdPost [^l]* cwindow | call setqflist([], 'a') | redraw!
	au FileType qf resize 20
augroup END


# Plug 'preservim/nerdtree'
#
g:NERDTreeDirArrows = 1
g:NERDTreeMinimalUI = 1
g:NERDTreeShowHidden = 1
g:NERDTreeMinimalMenu = 1
g:NERDTreeMapActivateNode = '<Space>'
g:NERDTreeWinSize = 40
g:NERDTreeDirArrowExpandable = '+'
g:NERDTreeDirArrowCollapsible = '-'
g:NERDTreeIgnore = [
	'^\.git$',
	'^\.direnv$',
]

map <F3> :NERDTreeToggle<CR>
map <leader>e :NERDTreeExplore<CR>
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') | quit | endif

# Plug 'tpope/vim-commentary'
#
augroup commentstring
	autocmd FileType c,h setlocal commentstring=//\ %s
augroup END

# Plug 'airblade/vim-gitgutter'
#
g:gitgutter_grep = 'rg'

autocmd BufWritePost * GitGutter

# Plug 'lifepillar/vim-mucomplete'
#
g:mucomplete#enable_auto_at_startup = 1
g:mucomplete#completion_delay = 100
g:mucomplete#reopen_immediately = 1

g:mucomplete#chains = {
	default: ['omni', 'keyn'],
	sql: ['keyn']
}
g:mucomplete#can_complete = {
	default: {
		omni: (t) => strlen(&l:omnifunc) > 0 && t =~# '\%(\k\|->\|::\|\.\)$',
	}
}

# mucomplete + vim-lsp
autocmd FileType go,rust setlocal omnifunc=lsp#complete
inoremap <leader>c <C-x><C-o>


# Plug 'prabirshrestha/vim-lsp'
#
# golang.org/x/tools/cmd/gopls
var gols = {
	name: 'gopls',
	cmd: (server_info) => ['gopls', 'serve'],
	root_uri: (server_info) => lsp#utils#path_to_uri(
		lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), ['go.mod', 'go.work'])
	),
	workspace_config: {
		gopls: {
			hoverKind: 'FullDocumentation',
			linksInHover: v:false,
			staticcheck: v:true,
		},
	},
	allowlist: ['go'],
	languageId: (server_info) => 'filetype',
}
au User lsp_setup lsp#register_server(gols)

# https://github.com/rust-lang/rust-analyzer
var rls = {
	name: 'rls',
	cmd: (server_info) => ['rust-analyzer'],
	root_uri: (server_info) => lsp#utils#path_to_uri(
		lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), ['Cargo.toml'])
	),
	initialization_options: {
		cargo: {buildScripts: {enable: v:true}},
		procMacro: {enable: v:true},
	},
	allowlist: ['rust'],
}
au User lsp_setup lsp#register_server(rls)

g:lsp_fold_enabled = 0
g:lsp_text_edit_enabled = 0
g:lsp_semantic_enabled = 0

g:lsp_diagnostics_echo_cursor = 1
g:lsp_diagnostics_virtual_text_enabled = 0

g:lsp_diagnostics_signs_error = {'text': 'x'}
g:lsp_diagnostics_signs_warning = {'text': 'w'}
g:lsp_diagnostics_signs_information = {'text': '@'}
g:lsp_diagnostics_signs_hint = {'text': '*'}
g:lsp_document_code_action_signs_hint = {'text': '>'}

g:lsp_format_sync_timeout = 1000

g:lsp_show_message_log_level = 'none'

nnoremap <silent> gd :LspDefinition<CR>
nnoremap <silent> gds :sp<CR>:LspDefinition<CR>
nnoremap <silent> gtd :LspTypeDefinition<CR>
nnoremap <silent> gi :LspImplementation<CR>
nnoremap <silent> gr :LspRename<CR>
nnoremap <silent> gn :LspNextError<CR>
nnoremap <silent> gp :LspPreviousError<CR>
nnoremap <silent> gx :LspReferences<CR>
nnoremap <silent> gh :LspHover<CR>

command! -bang -nargs=* LspStartServer lsp#activate()

augroup autoformat
	au FileType go,rust autocmd BufWritePre <buffer> :LspDocumentFormatSync
	au FileType go autocmd BufWritePre <buffer>
		\ execute('LspCodeActionSync source.organizeImports')

	au FileType proto autocmd BufWritePre <buffer> g:Format('clang-format -assume-filename=foobar.proto')
	au FileType c,cpp,hpp autocmd BufWritePre <buffer> g:Format('clang-format -assume-filename=foobar.c')
augroup END

def g:Format(formatter: string)
	var winview = winsaveview()

	var content = join(getbufline('%', 1, '$'), "\n")
	var formatted = systemlist(formatter, content)
	if v:shell_error == 0
		deletebufline('%', 1, '$')
		setline(1, [])
		setbufline('%', 1, formatted)
	else
		echoerr printf('Formatting failed: %s', formatted)
	endif

	winrestview(winview)
enddef

augroup filetypedetect
	au FileType python setlocal et sts=4 tw=80 cc=80
	au FileType yaml setlocal et sw=2 sts=2 ts=2
	au FileType proto setlocal et sts=4

	au FileType rst,markdown,text setlocal tw=80 cc=80 spell
	au FileType mail setlocal tw=72 cc=72 spell
	au FileType gitcommit setlocal tw=72 cc=72 spell
augroup END
