---
- name: Installing packages
  package:
    name: "{{ email_packages }}"
    state: latest

- name: Configure mbsync
  template:
    src: mbsyncrc.j2
    dest: "{{ email_home_dir }}/.mbsyncrc"

- name: Ensure himalaya config dir exists
  file:
    path: "{{ email_config_dir }}/himalaya"
    state: directory
    mode: 0755

- name: Configure himalaya
  template:
    src: himalaya/config.toml.j2
    dest: "{{ email_config_dir }}/himalaya/config.toml"
    mode: 0755
  notify: Restart himalaya

- name: Ensure himalaya service dirs exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ email_service_src }}/himalaya"
    - "{{ email_service_src }}/himalaya/log"

- name: Deploy himalaya runit service
  template:
    src: himalaya/sv/run.j2
    dest: "{{ email_service_src }}/himalaya/run"
    mode: 0755

- name: Deploy himalaya runit log script
  template:
    src: himalaya/sv/log-run.j2
    dest: "{{ email_service_src }}/himalaya/log/run"
    mode: 0755
  notify: Restart himalaya

- name: Start and enable himalaya runit service
  runit:
    name: himalaya
    state: started
    service_src: "{{ email_service_src }}"
    service_dir: "{{ email_service_dir }}"
    enabled: yes
