# General
export LANG=en_US.UTF-8
export EDITOR=vim
export CLICOLOR=YES
export SHELL=/bin/zsh
export LC_COLLATE=C

# LS_COLORS
[ -f $HOME/.dir_colors ] && eval "$(dircolors $HOME/.dir_colors)"

# PATH
typeset -U path
path+=($HOME'/.local/bin')
path+=($HOME'/.go/bin')
path+=($HOME'/.cargo/bin')
export PATH

export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Lang vars
export GOPATH=$HOME/.go
[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env
