# General
export LANG=en_US.UTF-8
export EDITOR=vim
export CLICOLOR=YES
export SHELL=/bin/zsh
export LC_COLLATE=C

export SVDIR=$HOME/.service

export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# PATH
typeset -U path
path+=($HOME"/.local/bin")
path+=($HOME"/.go/bin")
path+=($HOME"/.cargo/bin")
export PATH

# LS_COLORS
[ -f $HOME/.dir_colors ] && eval "$(dircolors $HOME/.dir_colors)"

# Lang vars
export GOPATH=$HOME/.go

export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
