## Settings
###########
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt inc_append_history
setopt no_hist_beep
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_save_no_dups
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_verify
setopt interactivecomments
# setopt share_history

setopt extended_glob
setopt noequals
setopt nobeep
setopt autocd
setopt nohup
setopt hash_cmds

## Completion
#############
autoload -Uz compinit
compinit
# autoload -Uz bashcompinit
# bashcompinit

zstyle ':completion:*' completer _expand _complete _ignored
zstyle :compinstall filename '~/.zshrc'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

## Bindings
###########
# delete
bindkey "^[[3~" delete-char

bindkey "^[e"   expand-cmd-path
bindkey " "     magic-space

# Home/End
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line

# PgUp/PgDn
bindkey "^[[5"  up-line-or-history
bindkey "^[[6"  down-line-or-history

# Up/Down
# disabled in favor of zsh-history-substring-search plugin
# bindkey "\e[A" history-search-backward
# bindkey "\e[B" history-search-forward

# Ctrl + Left/Right
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# Ctrl+k remove to eol
bindkey "\C-k" vi-kill-eol

## Aliases
##########
alias ls='ls --color'
alias ll='ls --color -hl'
alias grep="grep --colour"

alias tmux="tmux -u2"
alias curl="curl -s"

alias diff="diff -u --color"

alias nsxivd="nsxiv -r -t -s d"
alias magit="vim -c :MagitOnly"
alias notes="vim -c ':lcd ~/misc/notes'"

# void linux
alias xq="sudo xbps-query"
alias xr="sudo xbps-remove"

## Prompt
#########
autoload -Uz vcs_info
autoload -U promptinit
promptinit

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats "%b"
precmd() {
    vcs_info
}
setopt prompt_subst
PROMPT='%F{green}#%f %F{green}%n@%m: %F{yellow}%1~%f %F{magenta}[${vcs_info_msg_0_:0:30}]%f $ '
RPROMPT=''

## Plugins
##########
# https://github.com/zsh-users/zsh-history-substring-search
source ~/.zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

HISTORY_SUBSTRING_SEARCH_PREFIXED=true
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='fg=white,bold'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='fg=red,bold'

# https://github.com/zsh-users/zsh-autosuggestions
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# https://github.com/zsh-users/zsh-completions
fpath+=(~/.zsh/plugins/zsh-completions/src)

# https://github.com/junegunn/fzf
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

## Custom functions
###################
source ~/.zsh/func.zsh
